
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
---
apiVersion: v1
kind: Pod
metadata:
  name: astronomer-pod-template-file
  labels:
    tier: airflow
    component: worker
    release: ecliptical-kiloparsec-0984
    platform: astronomer
    workspace: clhkau3ah085714j38tkko8nq
spec:
  initContainers:
    
    - name: git-sync-init
      image: quay.io/astronomer/ap-git-sync:3.6.4-2
      imagePullPolicy: IfNotPresent
      securityContext: 
        runAsUser: 65533
      env:
        - name: GIT_SYNC_REV
          value: "HEAD"
        - name: GIT_SYNC_BRANCH
          value: "main"
        - name: GIT_SYNC_REPO
          value: "git://ecliptical-kiloparsec-0984-git-sync-relay.astronomer-ecliptical-kiloparsec-0984.svc.cluster.local.:9418/git"
        - name: GIT_SYNC_DEPTH
          value: "1"
        - name: GIT_SYNC_ROOT
          value: "/git"
        - name: GIT_SYNC_DEST
          value: "repo"
        - name: GIT_SYNC_ADD_USER
          value: "true"
        - name: GIT_SYNC_WAIT
          value: "1"
        - name: GIT_SYNC_MAX_SYNC_FAILURES
          value: "1"
        - name: GIT_SYNC_ONE_TIME
          value: "true"
        - name: GIT_SYNC_TIMEOUT
          value: "160"
      resources: 
          {}
      volumeMounts:
      - name: dags
        mountPath: /git
  containers:
    - args: []
      command: []
      envFrom:      
        []
      env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: LocalExecutor      
        # Hard Coded Airflow Envs
        - name: ASTRONOMER__AIRFLOW__WORKER_LOG_RETENTION_DAYS
          value: "3"
        - name: COMPONENT # Checked by entrypoint when sidecar logging is enabled
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['component']
        - name: AIRFLOW__CORE__FERNET_KEY
          valueFrom:
            secretKeyRef:
              name: ecliptical-kiloparsec-0984-fernet-key
              key: fernet-key
        # For Airflow <2.3, backward compatibility; moved to [database] in 2.3
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              name: ecliptical-kiloparsec-0984-airflow-metadata
              key: connection
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              name: ecliptical-kiloparsec-0984-airflow-metadata
              key: connection
        - name: AIRFLOW_CONN_AIRFLOW_DB
          valueFrom:
            secretKeyRef:
              name: ecliptical-kiloparsec-0984-airflow-metadata
              key: connection
        - name: AIRFLOW__WEBSERVER__SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ecliptical-kiloparsec-0984-webserver-secret-key
              key: webserver-secret-key
        # The elasticsearch variables were updated to the shorter names in v1.10.4
        - name: AIRFLOW__ELASTICSEARCH__HOST
          valueFrom:
            secretKeyRef:
              name: ecliptical-kiloparsec-0984-elasticsearch
              key: connection
        # This is the older format for these variable names, kept here for backward compatibility
        - name: AIRFLOW__ELASTICSEARCH__ELASTICSEARCH_HOST
          valueFrom:
            secretKeyRef:
              name: ecliptical-kiloparsec-0984-elasticsearch
              key: connection      
        # Dynamically created environment variables
        - name: AIRFLOW__ASTRONOMER__HOUSTON_JWK_URL
          value: "https://houston.sudarshan-astro32.astro-cre.com/v1/.well-known/jwks.json"
        - name: AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__AIRFLOW__ASTRONOMER__HOUSTON_JWK_URL
          value: "https://houston.sudarshan-astro32.astro-cre.com/v1/.well-known/jwks.json"
        - name: ASTRONOMER_ENVIRONMENT
          value: "software"
        - name: AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__ASTRONOMER_ENVIRONMENT
          value: "software"
        - name: AIRFLOW__WEBSERVER__UPDATE_FAB_PERMS
          value: "True"
        - name: AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__AIRFLOW__WEBSERVER__UPDATE_FAB_PERMS
          value: "True"
        - name: IMAGE_ARTIFACT
          value: "registry.sudarshan-astro32.astro-cre.com/ecliptical-kiloparsec-0984/airflow:deploy-1"
        - name: AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__IMAGE_ARTIFACT
          value: "registry.sudarshan-astro32.astro-cre.com/ecliptical-kiloparsec-0984/airflow:deploy-1"
        # Dynamically created secret envs
        
        # Extra env
      image: registry.sudarshan-astro32.astro-cre.com/ecliptical-kiloparsec-0984/airflow:deploy-1
      imagePullPolicy: IfNotPresent
      name: base
      ports: []
      volumeMounts:
        - mountPath: "/usr/local/airflow/logs"
          name: logs
        - name: config
          mountPath: "/usr/local/airflow/airflow.cfg"
          subPath: airflow.cfg
          readOnly: true
        - name: config
          mountPath: "/usr/local/airflow/config/airflow_local_settings.py"
          subPath: airflow_local_settings.py
          readOnly: true
        - name: dags
          mountPath: /usr/local/airflow/dags
          
          readOnly: True
  hostNetwork: false
  imagePullSecrets:
    - name: ecliptical-kiloparsec-0984-registry
  restartPolicy: Never
  securityContext:
    runAsUser: 50000
    fsGroup: 50000
  nodeSelector: 
    {}
  affinity: 
    {}
  tolerations: 
    []
  serviceAccountName: ecliptical-kiloparsec-0984-airflow-worker
  volumes:
  - name: dags
    emptyDir: {}
  - emptyDir: {}
    name: logs
  - configMap:
      name: ecliptical-kiloparsec-0984-airflow-config
    name: config